# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a24967ebb20a85da5ae5f24ff9d9388c0b0ba61bc34b4d32778742fcac218df82804bad7ccfcc1797abf35ec02b0ea7751b6b77ae32fb2e1c6f29929ff65714

test:
  secret_key_base: 1e4d1ee9856cdd19e1b7774f9251e87ac242db535f4690cbeea3b97c95d5826565d927717bade3abfbcffc5c6d54a78652be38aa9e1e9f59ac2821eb74d783b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
